--[[
  Jokes shamelessly stolen from:
    https://parade.com/998354/jessicasager/bad-jokes/
    https://parade.com/940979/kelseypelzer/best-dad-jokes/
    https://parade.com/1024249/marynliles/funny-puns/
]]


channel = "/echo"
delay_modifier = 10
repeat_threshold = 50

jokes = {
  -- https://parade.com/998354/jessicasager/bad-jokes/
  {"Why don't oysters donate to charity?", "Because they're shellfish."},
  {"What does a baby computer call its father?", "Data."},
  {"What did the custodian say when he jumped out of the closet?", "\"Supplies!\""},
  {"Why are colds bad criminals?", "Because they're easy to catch."},
  {"How does a penguin build its house?", "Igloos it together."},
  {"Which knight invented King Arthur's Round Table?", "Sir Cumference."},
  {"What do sprinters eat before a race?", "Nothing.", "They fast."},
  {"What do you call a fly without wings?", "A walk!"},
  {"What happens when you witness a ship wreck?", "You let it sink in."},
  {"How can you find Will Smith in the snow?", "Follow the fresh prints."},
  {"What does a clock do when it's hungry?", "It goes back four seconds."},
  {"What's the easiest way to make a glow worm happy?", "Cut off its tail—it'll be delighted!"},
  {"What do you call a belt made of watches?", "A waist of time!"},
  {"Why did Adele cross the road?", "To say hello from the other side!"},
  {"What's the best way to carve wood?", "Whittle by whittle."},
  {"What did the teacher do with the student's report on cheese?", "She grated it."},
  {"What's the difference between a piano and a fish?", "You can tune a piano, but you can't tuna fish."},
  {"What did the pirate say on his 80th birthday?", "\"Aye, matey!\""},
  {"How do you organize an astronomer's party?", "You planet."},
  {"What's the action like at a circus?", "In-tents."},
  {"Why did the scarecrow get promoted?", "Because he was outstanding in his field."},
  {"Why does Snoop Dogg carry an umbrella?", "Fo' drizzle."},
  {"What do you call a pony with a sore throat?", "A little hoarse."},
  {"What do you call a fish with no eye?", "Fsh."},
  {"What do you call a boomerang that doesn't come back?", "A stick!"},
  {"What kind of car does an egg drive?", "A Yolkswagen."},
  {"What do you call a factory that sells generally decent goods?", "A satisfactory."},
  {"Why was 6 afraid of 7?", "Because 7 ate 9."},
  {"Why should you never eat a clock?", "Because it's too time-consuming."},
  {"What should a sick bird do?", "Get tweetment."},
  {"I want a job cleaning mirrors.", "It's something I can really see myself doing."},
  {"What grades did the pirate get on his report card?", "Seven Cs."},
  {"How do you make a tissue dance?", "Put a little boogie in it."},
  {"How did Ebenezer Scrooge win the football game?", "The ghost of Christmas passed!"},
  {"Did you hear about the mediocre restaurant on the moon?", "It has great food but no atmosphere."},
  {"What kinds of pictures do hermit crabs take?", "Shellfies."},
  {"What do you get a man with the heart of a lion?", "A lifetime ban from the zoo."},
  {"What do you call a person with a briefcase in a tree?", "A branch manager."},
  {"Why did the baby cookie cry?", "Because its mother was a wafer so long."},
  {"What's the difference between an alligator and a crocodile?", "One you'll see later, the other you'll see in a while."},
  {"When is a door not really a door?", "When it's really ajar."},
  {"What do you do when you see a spaceman?", "Park in it, man."},
  {"Why do you never see elephants hiding in trees?", "Because they're so good at it!", "Why was the elephant painting his balls red?", "So he could hide in a cherry tree.", "What's the loudest sound in Africa?", "An giraffe eating cherries."},
  {"Did you hear about the claustrophobic astronaut?", "Poor guy really needed some space."},
  {"What's the No. 1 cause of divorce?", "Marriage!"},
  {"Why did the coffee call the police?", "It got mugged!"},
  {"Why did Cyclops close his school?", "He only had one pupil."},
  {"Where do skunks pray?", "In pews."},
  {"If you're American when you come out of the bathroom, what are you when you're in the bathroom?", "European."},
  {"Why do birds fly south for the winter?", "Because it's too far to walk."},
  {"How did Darth Vader know what Luke Skywalker got him for Christmas?", "He felt his presents."},
  {"What was the mummy's favorite type of music?", "Wrap."},
  {"I'm only familiar with 25 letters of the alphabet. I don't know why."},
  {"Did you hear about the beautiful wedding?", "Even the cake was in tiers."},
  {"Why are there fences are cemeteries?", "Because everyone's always dying to get in."},
  {"A company is making glass coffins. Whether they're successful remains to be seen."},
  {"What did one wall say to the other?", "\"Meet me at the corner!\""},
  {"What do you call a large African mammal with long hair and sandals?", "A hippie-potamus."},
  {"How do you think the unthinkable?", "With an itheberg!"},
  {"What's the award for being the best dentist?", "A plaque."},
  {"Why can't you hear a pterodactyl go to the bathroom?", "Because the P is silent."},
  {"I bought sneakers from a drug dealer. I don't know what he laced them with but I've been tripping all day!"},
  {"Why did Mozart hate chickens?", "Because when he asked them for their favorite composer, they said, \"Bach! Bach! Bach!\""},
  {"Why did the toilet paper roll downhill?", "To get to the bottom."},
  {"What's the best name for a man who can't stand?", "Neil."},
  {"What do you call a deer with no eyes?", "No eyed deer."},
  {"Why are groups of fish so smart?", "Because they travel in schools."},
  {"How much does the heaviest skeleton weigh?", "A skeleton."},
  {"What did the drummer name her twin daughters?", "Anna One, Anna Two."},
  {"What's big, gray and doesn't matter?", "An irrelephant."},
  {"Why did the snowman pick through a bag of carrots?", "Because he was picking his nose."},
  {"Why does Waldo only wear stripes?", "Because he doesn't want to be spotted."},
  {"I witnessed an attempted murder earlier—fortunately only one crow showed up!"},
  {"I tried buying camouflage the other day but I couldn't find any."},
  {"What did one bean say to the other?", "\"How you bean?\""},
  {"How do you catch a bra?", "With a booby trap."},
  {"How many tickles can an octopus take?", "Tentacles!"},
  {"What do clouds wear under their shorts?", "Thunderpants."},
  {"Did you hear about the guy who won the award for best knock knock joke?", "He won the no bell prize."},
  {"Why did Cinderella get kicked off of the soccer team?", "Because she kept running from the ball!"},
  {"How many ears do space aliens have?", "Three: The left ear, right ear and the final front ear."},
  {"Cosmetic surgery used to be taboo, but now when you talk about Botox no one raises an eyebrow."},
  {"Did you hear the one about the three watering holes in the ground?", "Well, well, well..."},
  {"What did the socks say to the pants?", "\"'Sup britches?!\""},
  {"What shivers at the bottom of the ocean?", "A nervous wreck."},
  {"What's a ninja's favorite type of shoes?", "Sneakers!"},
  {"I have the world's worst thesaurus. Not only is it terrible, it's also terrible."},
  {"What do hillbillies drink from?", "Hiccups."},
  {"What's even better than Ted Danson?", "Ted singing and Danson."},
  {"Why did the invisible man turn down a job offer?", "He couldn't see himself doing it."},
  {"What kind of music do windmills like?", "They're metal fans."},
  {"What do you call a fish with two knees?", "A tunee fish."},
  {"I'd tell you the joke about perforated paper, but it's tear-able."},
  {"What do you call someone else's cheese?", "Nacho cheese!"},
  {"What do you call a canine magician?", "A labracadabrador."},
  {"The rotation of the earth really makes my day."},
  {"Why do seagulls fly over the sea?", "Because if they flew over the bay, they'd be called bagels."},
  {"What did the animals tell Simba when he walked too slow?", "Mufasa!"},
  {"What do you call Samsung's security team?", "The Guardians of the Galaxy!"},
  {"I sold my vacuum yesterday. It was just collecting dust."},
  {"What kind of tea is the hardest to swallow?", "Reality."},
  {"Why did the golfer need new pants?", "Because he got a hole in one."},
  {"Why did the man get fired from the calendar factory?", "Because he took a few days off."},
  {"What do you call an alligator wearing a vest?", "An investigator."},
  {"How do snails fight?", "They slug it out."},
  {"What's Forrest Gump's email password?", "1forrest1."},
  {"What did the left butt cheek say to the right butt cheek?", "\"You crack me up!\""},
  {"What do you call someone who points out the obvious?", "Someone who points out the obvious."},
  {"What sound does a nut make when it sneezes?", "Cashew!"},
  {"Did you hear about the satellites' wedding?", "The ceremony was OK, but the reception was terrific."},
  {"What did the Atlantic Ocean say to the Pacific Ocean?", "Nothing, it just waved."},
  {"What did the fish say when it swam into the wall?", "\"Dam!\""},
  {"Which school supply is king?", "The ruler."},
  {"What do you get when you cross a vampire with a snowman?", "Frostbite."},
  {"What do you call a person with no body and no nose?", "Nobody knows."},
  {"What's green and sings?", "Elvis Parsley."},
  {"How do you make holy water?", "You boil the hell out of it."},
  {"A jumper cable walks into a bar.", "The bartender says, \"I'll serve you, but don't start anything.\""},
  {"What's the worst part of being an egg?", "You only get laid once (and it's with your mom)!"},
  {"Three fish are in a tank.", "One asked the others, \"How the heck do you drive this thing?\""},
  {"What concert is worth just 45 cents?", "50 Cent and Nickelback."},
  {"Why can't a hand be 12 inches long?", "Because then it'd be a foot."},
  {"What's the difference between a dapper man on a bicycle and a poorly dressed man on a unicycle?", "Attire!"},
  {"I left my job at a shoe disposal plant. It was sole destroying."},
  {"The past, the present and the future walked into a bar.", "It was tense."},
  {"What did Eminem say when 50 Cent made him a sweater?", "\"Gee, you knit?\""},
  {"What did the thumb say to the finger?", "\"I'm in glove with you.\""},
  {"What does a nosy pepper do?", "It gets jalapeno business!"},
  {"Parallel lines have so much in common.", "It's a shame they'll never meet."},
  {"There are three types of people in this world: People who are good at math and people who are not."},
  {"What do you call an Italian astronaut?", "A specimen."},
  {"Two guys walk into a bar. The third guy ducks."},
  {"Why do ghosts love elevators?", "Because they lift their spirits."},
  {"What do you call a snobby criminal going downstairs?", "A condescending con descending."},
  {"What did the princess say in the photo booth?", "\"Someday my prints will come.\""},
  {"What can you do if you're scared of elevators?", "Take steps to avoid them."},
  {"What's brass and sounds like Tom Jones?", "Trombones."},
  {"How do prisoners communicate with one another?", "Cell phones."},
  {"How many bugs do you need to rent out an apartment?", "Tenants."},
  {"What did one elevator say to the other?", "\"I think I'm coming down with something.\""},
  {"What's a foot's favorite snack?", "Dori-toes."},
  {"The shovel was a truly groundbreaking invention."},
  {"What did Sushi A say to Sushi B?", "\"Wasa-B!\""},
  {"You know why they called it \"the dark ages?\"", "There were too many knights."},
  {"What's the loudest kind of pet you can get?", "A trumpet."},
  {"Two cannibals are eating a clown. One asks the other, \"Does this taste funny to you?\""},
  {"Does anyone need an ark?", "I Noah guy."},
  {"Why did the picture go to jail?", "Because it was framed!"},
  {"Why did the melons have a big wedding?", "Because they cantaloupe."},
  {"Have you heard the joke about the bed?", "No?", "That's because it hasn't been made yet."},
  {"Why can't wildcats take tests?", "There are too many cheetahs."},
  {"What do you call a can opener that doesn't work?", "A can't opener."},
  {"Why shouldn't you make a \"dad joke\" if you're not a dad?", "Because it's a faux pa."},
  {"A man died after drinking varnish. It was a terrible end, but a beautiful finish."},
  {"What's the difference between Prince William and a tennis ball?", "One is heir to the throne and one is thrown in the air."},
  {"What's the derivative of Amazon?", "Amazon Prime."},
  {"Why couldn't the pirate sit down?", "His booty got stolen!"},
  {"Why was the broom late for a meeting?", "It overswept."},
  {"How did the hipster burn his mouth?", "He sipped his coffee before it was cool."},
  {"What did the over-excited gardener do when spring came?", "She wet her plants."},
  {"What do you call Batman if he skips church?", "Christian Bale!"},
  {"I used to hate body hair, but then it grew on me."},
  {"What do you call a bear with no teeth?", "A gummy bear."},
  {"What kind of dinosaur has the biggest vocabulary?", "The thesaurus!"},
  {"What did the grape do when it got stomped on?", "It let out a little wine."},
  {"What's the best part about Switzerland?", "The flag is a big plus."},
  {"What did the buffalo say when his son left?", "Bison!"},
  {"What do you call a fake noodle?", "An impasta!"},
  {"Did you know the first French fries weren't cooked in France?", "They were cooked in Greece!"},
  {"What do carb-loving zombies eat?", "Graaaaaaaains."},
  {"What's the best time to see a dentist?", "Tooth hurty."},
  {"What's the difference between a hippo and a Zippo?", "One is heavy and one is a lot lighter."},
  {"Why shouldn't you write with a dull pencil?", "Because it's pointless."},
  {"How much does an influencer weigh?", "An Instagram."},
  {"What do you get when you combine a rhetorical question and a joke?"},
  -- https://parade.com/940979/kelseypelzer/best-dad-jokes/
  {"Which bear is the most condescending?", "A pan-duh!"},
  {"What kind of noise does a witch’s vehicle make?", "Brrrroooom, brrroooom."},
  {"My girlfriend keeps accusing me of cheating.", "She's starting to sound like my wife."},
  {"What’s brown and sticky?", "A stick."},
  {"Two guys walked into a bar.", "The third guy ducked."},
  {"Did you hear about the actor who broke his leg onstage?", "He's still in the cast."},
  {"How do you get a country girl’s attention?", "A tractor."},
  {"What do you call it when a group of apes starts a company?", "Monkey business."},
  {"Why did the pharmacist walk on her tiptoes?", "She didn't want to wake the sleeping pills."},
  {"I wanted to buy a pair of camouflage pants, but I couldn't find any."},
  {"Why are elevator jokes so classic and good?", "They work on many levels."},
  {"I have an inferiority complex, but it's not a very good one."},
  {"What do you call a pudgy psychic?", "A four-chin teller."},
  {"I had a date last night and it was perfect.", "Tomorrow, I’ll have a fig."},
  {"What did the police officer say to his belly-button?", "You’re under a vest."},
  {"My wife asked me to stop singing “Wonderwall” to her.", "I said \"Maybe...\""},
  {"What kind of drink can be bitter and sweet?", "Reali-tea."},
  {"What do you call a naughty lamb dressed up like a skeleton for Halloween?", "Baaad to the bone."},
  {"Why did the lobster blush?", "Because it saw the ocean's bottom!"},
  {"Want to know why nurses like red crayons?", "Sometimes they have to draw blood."},
  {"What would the Terminator be called in his retirement?", "The Exterminator."},
  {"What did Tennessee?", "The same thing as Arkansas."},
  {"My wife asked me to go get 6 cans of Sprite from the grocery store.", "I realized when I got home that I had picked 7 up."},
  {"Why do bees have sticky hair?", "Because they use a honeycomb."},
  {"Why do some couples go to the gym?", "Because they want their relationship to work out."},
  {"What do you call an angry musician flipping someone off?", "A song bird."},
  {"What’s the most detail-oriented ocean?", "The Pacific."},
  {"Did you hear about the kidnapping at school?", "It’s fine, he woke up."},
  {"How can you tell it’s a dogwood tree?", "By the bark."},
  {"My boss told me to have a good day, so I went home."},
  {"Our vacuum cleaner is getting old.", "It's just gathering dust."},
  {"Why did the man fall down the well?", "Because he couldn’t see that well."},
  {"When does a joke become a “dad joke”?", "When it becomes apparent."},
  {"Why is Peter Pan always flying?", "Because he Neverlands."},
  {"Which state has the most streets?", "Rhode Island."},
  {"What do you call 26 letters that went for a swim?", "Alphawetical."},
  {"What’s the name of a very polite, European body of water?", "Merci."},
  {"Why was the color green notoriously single?", "It was always so jaded."},
  {"I used to hate facial hair, but then it grew on me."},
  {"I want to make a brief joke, but it’s a little cheesy."},
  {"Why did the coach go to the bank?", "To get his quarterback."},
  {"How do celebrities stay cool?", "They have many fans."},
  {"Sundays are always a little sad, but the day before is a sadder day."},
  {"5/4 of people admit they’re bad at fractions."},
  {"Why did the bedding hide their relationship?", "They just wanted something pillow-key!"},
  {"You’re American when you go into a bathroom and when you come out, but what are you while you’re in the bathroom?", "European."},
  {"I’ve been thinking about taking up meditation.", "I figure it’s better than sitting around doing nothing."},
  {"Dogs can’t operate MRI machines.", "But catscan."},
  {"What did the flowers do when the bride walked down the aisle?", "They rose."},
  {"It takes guts to be an organ donor."},
  {"What do you get from a pampered cow?", "Spoiled milk."},
  {"What does \"Rockin' Robin\" do when she's bored?", "Tweet."},
  {"I lost my job at the bank on my first day.", "A woman asked me to check her balance, so I pushed her over."},
  {"Why did Waldo go to therapy?", "Because he needed to find himself."},
  {"How do you row a canoe filled with puppies?", "Bring out the doggy paddle."},
  {"Singing in the shower is fun until you get soap in your mouth.", "Then it becomes a soap opera."},
  {"Why were the utensils stuck together?", "They were spooning."},
  {"What's a crafty dancer's favorite hobby?", "Cutting a rug."},
  {"How does a penguin build his house?", "Igloos it together."},
  {"What kind of music do chiropractors like?", "Hip pop."},
  {"Where do you learn to make ice cream?", "At sundae school."},
  {"What kind of shoes does a lazy person wear?", "Loafers."},
  {"Why is cold water so insecure?", "Because it’s never called hot."},
  {"How many apples can you grow on a tree?", "All of them."},
  {"Why can't you trust an atom?", "Because they make up everything."},
  {"Justice is a dish best served cold.", "If it were served warm, it would be just-water."},
  {"I was going to tell a time-traveling joke, but you guys didn’t like it."},
  {"Shouldn’t the “roof” of your mouth actually be called the ceiling?"},
  {"Why did the baby strawberry cry?", "Because its mother was in a jam."},
  {"Why couldn't the toilet paper cross the road?", "Because it got stuck in a crack."},
  {"Stop looking for the perfect match…use a lighter."},
  {"I told my doctor I heard buzzing, but he said it’s just a bug going around."},
  {"What kind of car does a sheep like to drive?", "A  Lamborghini."},
  {"What do you call someone who won't stick to a diet?", "A desserter."},
  {"What did the accountant say while auditing a document?", "This is taxing."},
  {"What did the two pieces of bread say on their wedding day?", "It was loaf at first sight."},
  {"If you see a burglary at an Apple store, you become an iWitness."},
  {"If the early bird gets the worm, I’ll sleep in until there’s pancakes."},
  {"Why do melons have weddings?", "Because they cantaloupe."},
  {"I signed up for a marathon, but how will I know if it’s the real deal or just a run through?"},
  {"When you have a bladder infection, urine trouble."},
  {"What did the drummer call his twin daughters?", "Anna One, Anna Two!"},
  {"What did the juicer say to the orange during self-quarantine?", "Can’t wait to squeeze you!"},
  {"What do you call a toothless bear?", "A gummy bear!"},
  {"Want to hear a joke about construction?", "I’m still working on it."},
  {"Someone told me that I should write a book.", "I said, “That’s a novel concept.”"},
  {"Two goldfish are in a tank.", "One says to the other, “Do you know how to drive this thing?”"},
  {"Why did the pony ask for a glass of water?", "Because it was a little horse."},
  {"What's Forrest Gump's password?", "1forrest1"},
  {"I tell dad jokes, but I don’t have any kids.", "I’m a faux pa."},
  {"What does a nosey pepper do?", "It gets jalapeño business."},
  {"How can you mend a broken pumpkin?", "Use a pumpkin patch."},
  {"If a child refuses to nap, are they guilty of resisting a rest?"},
  {"Why do dads feel the need to tell such bad jokes?", "They just want to help you become a groan up."},
  {"I know a lot of jokes about retired people, but none of them work."},
  {"Why are spiders so smart?", "They can find everything on the web."},
  {"What do you call spiders who just got married?", "Newly-webs."},
  {"RIP boiled water—you will be mist."},
  {"What do you call two octopuses that look the same?", "Itenticle."},
  {"What has one head, one foot, and four legs?", "A bed."},
  {"Sore throats are a pain in the neck."},
  {"What does a house wear?", "Address."},
  {"Why did the scarecrow win an award?", "He was out standing in his field."},
  {"What is a scarecrow's favorite fruit?", "Straw-berries."},
  {"What’s red and smells like blue paint?", "Red paint."},
  {"My son asked me to put his shoes on, but I don’t think they’ll fit me."},
  {"I’ve been bored recently, so I decided to take up fencing.", "The neighbors keep demanding that I put it back."},
  {"How do you know when a chicken is evil?", "It lays deviled eggs."},
  {"What do you call an unpredictable camera?", "A loose Canon."},
  {"I didn’t get a haircut, I got them all cut."},
  {"Which U.S.", "state is known for its especially small soft drinks?", "Minnesota."},
  {"What do sprinters eat before a race?", "Nothing—they fast."},
  {"What did one Dorito farmer say to the other?", "“Cool Ranch!”"},
  {"How do cows shop?", "From cattle-logs."},
  {"I’m so good at sleeping, I can do it with my eyes closed."},
  {"People are usually shocked that I have a Police record.", "But I love their greatest hits!"},
  {"I told my girlfriend she drew on her eyebrows too high.", "She seemed surprised."},
  {"What do you call a fibbing cat?", "A lion."},
  {"Why shouldn’t you write with a broken pencil?", "Because it’s pointless."},
  {"I like telling Dad jokes…sometimes he laughs."},
  {"How do you weigh a millennial?", "In Instagrams."},
  {"The wedding was so beautiful, even the cake was in tiers."},
  {"What’s the most patriotic sport?", "Flag football."},
  {"Why were spectators confused by the koala's self-portrait?", "It was bear."},
  {"Why did the envelope take so long to get ready?", "It had to get addressed."},
  {"What does a karate master get rewarded with while driving?", "A seat belt."},
  {"What do you call a baby sheep that knows karate?", "A lamb chop."},
  {"What did the husband say to his wife right after getting LASIK surgery?", "\"Aren't you a sight for sore eyes?\""},
  {"Why are pigs bad drivers?", "Because they hog the road."},
  {"What do lions use to look at their manes?", "Mirroars."},
  {"What did the dad say when his golden retriever was caught eating a hot dog?", "\"It's a dog eat dog world out there.\""},
  {"Do mascara and lipstick ever argue?", "Sure, but then they makeup."},
  {"What piece on the playground is always exhausted?", "The tire swing."},
  {"Why did two tall people get along so well?", "They could really see eye to eye."},
  {"Why was the gossip disliked at the coffee shop?", "She always spilled the tea."},
  {"What does a writer have in common with a football player?", "Anxiety over a rough draft."},
  {"Where do wasps like to get lunch?", "A bee-stro."},
  {"Is there anything worse than when it's raining cats and dogs?", "Yes! Hailing taxis."},
  {"Why would doors do well on social media?", "Everyone looks for their handles."},
  {"Why did the physicist and the biologist break up?", "Because they had no chemistry."},
  {"If you feel like someone is watching you, you're not alone."},
  {"Which bathroom appliance would be the worst life preserver?", "The sink."},
  {"Why was the dad sitting on a pack of playing cards?", "His kid asked him to sit on the deck."},
  {"How do birds learn how to fly?", "They wing it!"},
  {"What kind of bird is always getting hurt?", "The owl."},
  {"What's either a really gross animal issue OR an impressive, magical school?", "Hogwarts."},
  {"How does Darth Vader like his toast?", "On the dark side."},
  {"What did the dishwasher say to the oven after a productive day?", "\"You've been on fire!\""},
  {"Why did the tomato blush?", "Because it saw the salad dressing."},
  {"Why did the cashier rip money in half?", "They were asked to break a bill."},
  {"What did one furniture maker say to another during a tense discussion?", "\"Let's table this.\""},
  {"I was going to tell a joke about water, but it was too tasteless."},
  {"Why couldn't the duck be quiet?", "Because it was addicted to quack."},
  {"Why was the ghost so tired?", "He worked the graveyard shift."},
  {"Why do pancakes always win at baseball?", "They have the best batter."},
  {"Why did the baseball player get arrested?", "Because he stole second base."},
  {"Why couldn't the couple get married at the library?", "It was all booked up."},
  {"Why did the pug buy a clock?", "It wanted to be a watchdog."},
  {"Where do hamburgers go to dance?", "The meatball."},
  {"How did the dad prank his daughter using fake dog poop on April Fools Day?", "He told her to look out for her new sham-poo in the shower."},
  {"What did the air conditioner say when it met a celebrity?", "\"I'm a big fan.\""},
  {"What was Sherlock Holmes' favorite protein source?", "Mystery meat."},
  {"What did the dryer say to the boring duvet cover that just got out of the washer?", "\"Don't be such a wet blanket.\""},
  {"Why couldn't the bike stand up on its own?", "Because it was too tired."},
  {"Why was the cow such a heartthrob on the farm?", "He was a s-moo-th talker."},
  {"What's a writer's favorite train station?", "Penn Station."},
  {"What do you call a gnat with a sore throat?", "A hoarse fly."},
  {"What was said about the messy, angry man who was eating a can of Pringles?", "\"He's got a chip on his shoulder.\""},
  {"What's it called when kittens get stuck in a tree?", "A cat-astrophe."},
  {"What kind of shape may have been knighted?", "Cir-cles."},
  {"Why is sand so optimistic?", "It has a can-dune attitude."},
  {"What has four wheels and flies?", "A garbage truck."},
  {"What part of the museum makes everyone sneeze?", "The sta-tues."},
  {"What did the baker say when she won an award?", "\"It was a piece of cake.\""},
  {"Why couldn't the couple respond right away when looking at wedding venues?", "They were engaged."},
  {"What is Marco's favorite clothing store?", "Polo."},
  {"What do you call it when a lawyer takes a test early in the morning?", "A breakfast bar."},
  {"What do frogs use to track their exercise?", "Fit (rib)bits."},
  {"How do frogs invest their money?", "They use a stock croaker."},
  {"Why did police arrest the turkey?", "They suspected fowl play."},
  {"What kind of cleaning product feels a lot of motivation in life?", "All-purpose."},
  {"Where was the dripping coming from in the fridge?", "The leeks."},
  {"Why was the hockey player gifted a new cap?", "He was known for his hat tricks."},
  {"What vegetable is kind to everyone?", "The sweet potato."},
  {"How was the handsome runner described?", "\"Dashing.\""},
  {"What animals are the best to call if you get locked out of your house?", "Monkeys."},
  {"What did the geometry teacher say when the class had trouble solving a problem?", "\"Let's try a different angle.\""},
  {"Why don't phones ever go hungry?", "They have plenty of apps to choose from."},
  {"Why couldn't the family leave the room after playing with Legos?", "They were blocked."},
  {"What makes a basketball court trendy and accessorized?", "The hoops."},
  {"What did the sapphire's best friend tell her?", "\"You're a real gem.\""},
  {"Getting paid to sleep is a true dream job."},
  {"Did you hear about the bossy man at the bar?", "He ordered everyone around."},
  {"What do you give the dentist of the year?", "A little plaque."},
  {"Why did the deer go to the dentist?", "It had buck teeth."},
  {"Why did the Oreo go to the dentist?", "Because it lost its filling."},
  {"What happens when doctors get frustrated?", "They lose their patients."},
  {"Why was the traffic light late to work?", "It took too long to change."},
  {"Did you hear about the guy who was afraid of hurdles?", "He got over it."},
  {"Why didn’t the sun go to college?", "It already had a million degrees."},
  {"Did you hear about the guy who drank invisible ink?", "He's at the hospital waiting to be seen."},
  {"What do you call a can opener that doesn't work?", "A can't opener.", ""},
  {"What do lawyers wear to work?", "Law suits."},
  {"I used to be a banker, but I lost interest."},
  {"Why did the computer catch cold?", "It left a window open."},
  {"What do computers eat for a snack?", "Microchips."},
  {"Why did the computer go to bed?", "It needed to crash."},
  {"Why did the employee get fired from the keyboard factory?", "He wasn't putting in enough shifts."},
  {"How do trees get on the internet?", "They log in."},
  {"Why did the computer get glasses?", "To improve its website."},
  {"What kind of bird works on a construction site?", "A crane."},
  {"How much money does a skunk have?", "Only one scent."},
  {"Why did the watch go on vacation?", "Because it needed to unwind."},
  {"What does a painter do when he gets cold?", "Puts on another coat."},
  {"How do you tell a scientist that they have bad breath?", "Offer them an experi-mint."},
  {"How did the barber win the race?", "He knew a shortcut."},
  {"Why did the roofer go to the doctor?", "He had shingles."},
  {"Dogs can’t operate MRI machines, but cats-can."},
  {"What does a librarian use to go fishing?", "A bookworm."},
  {"What did the roof say to the shingle?", "The first one is on the house."},
  {"Why did the tailor get fired?", "He wasn’t a good fit."},
  {"What kind of bug can tell time?", "A clock-roach."},
  {"Why did the girl toss a clock out the window?", "She wanted to see time fly."},
  {"When does Friday come before Thursday?", "In the dictionary."},
  -- https://parade.com/1024249/marynliles/funny-puns/
  {"Why did Adele cross the road?", "To say hello from the other side."},
  {"What kind of concert only costs 45 cents?", "A 50 Cent concert featuring Nickelback."},
  {"What did the grape say when it got crushed?", "Nothing, it just let out a little wine."},
  {"I want to be cremated as it is my last hope for a smoking hot body."},
  {"Time flies like an arrow.", "Fruit flies like a banana."},
  {"To the guy who invented zero, thanks for nothing."},
  {"I had a crazy dream last night! I was swimming in an ocean of orange soda.", "Turns out it was just a Fanta sea."},
  {"A crazy wife says to her husband that moose are falling from the sky.", "The husband says, it’s reindeer."},
  {"Ladies, if he can’t appreciate your fruit jokes, you need to let that mango."},
  {"Geology rocks but Geography is where it’s at!"},
  {"What was Forrest Gump’s email password?", "1forrest1"},
  {"Did you hear about the restaurant on the moon?", "I heard the food was good but it had no atmosphere."},
  {"Can February March?", "No, but April May."},
  {"Need an ark to save two of every animal?", "I noah guy."},
  {"I don’t trust stairs because they’re always up to something."},
  {"Smaller babies may be delivered by stork but the heavier ones need a crane."},
  {"My grandpa has the heart of the lion and a lifetime ban from the zoo."},
  {"Why was Dumbo sad?", "He felt irrelephant."},
  {"A man sued an airline company after it lost his luggage.", "Sadly, he lost his case."},
  {"I lost my mood ring and I don't know how to feel about it!"},
  {"Yesterday, I accidentally swallowed some food coloring.", "The doctor says I’m okay, but I feel like I’ve dyed a little inside."},
  {"So what if I don’t know what apocalypse means?", "It’s not the end of the world!"},
  {"My friend drove his expensive car into a tree and found out how his Mercedes bends."},
  {"Becoming a vegetarian is one big missed steak."},
  {"I was wondering why the ball was getting bigger.", "Then it hit me."},
  {"Some aquatic mammals at the zoo escaped.", "It was otter chaos!"},
  {"Never trust an atom, they make up everything!"},
  {"Waking up this morning was an eye-opening experience."},
  {"Long fairy tales have a tendency to dragon."},
  {"What do you use to cut a Roman Emperor's hair?", "Ceasers."},
  {"The Middle Ages were called the Dark Ages because there were too many knights."},
  {"My sister bet that I couldn’t build a car out of spaghetti.", "You should’ve seen her face when I drove pasta."},
  {"I made a pun about the wind but it blows."},
  {"Never discuss infinity with a mathematician, they can go on about it forever."},
  {"I knew a guy who collected candy canes, they were all in mint condition."},
  {"My wife tried to apply at the post office but they wouldn’t letter.", "They said only mails work here."},
  {"My friend’s bakery burned down last night.", "Now his business is toast."},
  {"Getting the ability to fly would be so uplifting."},
  {"It's hard to explain puns to kleptomaniacs because they always take things literally."},
  {"Two windmills are standing in a wind farm.", "One asks, \"What’s your favorite kind of music?\" The other says, \"I’m a big metal fan.\""},
  {"I can’t believe I got fired from the calendar factory.", "All I did was take a day off!"},
  {"England doesn't have a kidney bank, but it does have a Liverpool."},
  {"What do you call the wife of a hippie?", "A Mississippi."},
  {"A cross-eyed teacher couldn’t control his pupils."},
  {"She had a photographic memory, but never developed it."},
  {"I wasn’t originally going to get a brain transplant, but then I changed my mind."},
  {"There was a kidnapping at school yesterday.", "Don’t worry, though - he woke up!"},
  {"What do you get when you mix alcohol and literature?", "Tequila mockingbird."},
  {"What washes up on tiny beaches?", "Microwaves."},
  {"I hate how funerals are always at 9 a.m.", "I’m not really a mourning person."},
  {"What’s the difference between a poorly dressed man on a bicycle and a nicely dressed man on a tricycle?", "A tire."},
  {"The guy who invented the door knocker got a no-bell prize."},
  {"German sausage jokes are just the wurst."},
  {"What do you call an alligator in a vest?", "An investigator."},
  {"What do you call the ghost of a chicken?", "A poultry-geist."},
  {"How does Moses make coffee?", "Hebrews it."},
  {"The machine at the coin factory just suddenly stopped working, with no explanation.", "It doesn’t make any cents."},
  {"Sure, I drink brake fluid.", "But I can stop anytime!"},
  {"What do you call a man with no arms and no legs stuffed in your mailbox?", "Bill."},
  {"Somebody stole all my lamps.", "I couldn’t be more de-lighted!"},
  {"I bought a boat because it was for sail."},
  {"I'm reading a book about anti-gravity.", "It's impossible to put down!"},
  {"How did the picture end up in jail?", "It was framed!"},
  {"My ex-wife still misses me.", "But her aim is starting to improve!"},
  {"Coffee has a rough time in our house.", "It gets mugged every single morning!"},
  {"Why was the cookie sad?", "Because his mom was a wafer long!"},
  {"What's the difference between a hippo and a zippo?", "One is really heavy and the other is a little lighter!"},
  {"What did the sushi say to the bee?", "Wasabee!"},
  {"Why was the baby ant confused?", "Because all his uncles were ants!"},
  {"I just found out that I'm color blind.", "The news came completely out of the green!"},
  {"Why didn't the cat go to the vet?", "He was feline fine!"},
  {"Who is the penguin's favorite Aunt?", "Aunt-Arctica!"},
  {"What should a lawyer always wear to a court?", "A good lawsuit!"},
  {"The quickest way to make antifreeze?", "Just steal her blanket!"},
  {"How do you make a good egg-roll?", "You push it down a hill!"},
  {"Apple is designing a new automatic car.", "But they're having trouble installing Windows!"},
  {"I've started sleeping in our fireplace.", "Now I sleep like a log!"},
  {"That baseball player was such a bad sport.", "He stole third base and then just went home!"},
  {"Did you hear about the guy who got hit in the head with a can of soda?", "He was lucky it was a soft drink!"},
  {"The past, the present, and the future walk into a bar.", "It was tense!"},
  {"You really shouldn't be intimidated by advanced math… it's easy as pi!"},
  {"What did the hamburger name its baby?", "Patty!"},
  {"One lung said to another: \"We be-lung together!\""},
  {"I asked a Frenchman if he played video games.", "He said Wii."},
  {"Why are frogs so happy?", "They eat whatever bugs them."},
  {"What did the duck say when she purchased new lipstick?", "Put it on my bill!"},
  {"My parents said I can't drink coffee anymore.", "Or else they'll ground me!"},
  {"What did syrup to the waffle?", "I love you a waffle lot!"},
  {"My wife refuses to go to a nude beach with me.", "I think she's just being clothes-minded!"},
  {"Did you hear about that cheese factory that exploded in France?", "There was nothing left but de Brie!"},
  {"I'm no cheetah, you're lion!"},
  {"What did the ranch say when somebody opened the refrigerator?", "\"Hey, close the door! I'm dressing!\""},
  {"I wanted to take pictures of the fog this morning but I mist my chance.", "I guess I could dew it tomorrow!"},
  {"My dad unfortunately passed away when we couldn't remember his blood type.", "His last words to us were, \"Be positive!\""},
  {"What do you call a girl with one leg that's shorter than the other?", "Ilene."},
  {"Towels can’t tell jokes.", "They have a dry sense of humor."},
  {"What did the buffalo say to his son?", "Bison."},
  {"Why should you never trust a train?", "They have loco motives."},
  {"A cabbage and celery walk into a bar and the cabbage gets served first because he was a head."},
  {"What’s America's favorite soda?", "Mini soda."},
  {"What does a clock do when it's hungry?", "It goes back for seconds."},
}

next_number = math.random(1,#jokes)

if type(repeat_threshold)=="number" then
  if #jokes<=repeat_threshold then
    yield("/echo repeat_threshold = "..repeat_threshold..", but there's only "..#jokes.." jokes in the list.")
    yield("/echo Are you trying to break things? Stop it.")
    repeat_threshold = #jokes-1
  end
  jokes_told = {}

  ::Load::
  jokes_told_file = os.getenv("appdata").."\\XIVLauncher\\pluginConfigs\\SomethingNeedDoing\\jokes_told.txt"
  f=io.open(jokes_told_file,"r")
  if f~=nil then
    io.close(f)
    jokes_told = {}
    file_jokes_told = io.input(jokes_told_file)
    next_line = file_jokes_told:read("l")
    while next_line do
      table.insert(jokes_told,tostring(next_line))
      next_line = file_jokes_told:read("l")
    end
    file_jokes_told:close()
  end
  if #jokes_told>=#jokes then jokes_told = {} end

  ::Check::
  for _, joke_test in pairs(jokes_told) do
    if tostring(next_number)==joke_test then
      repeat_joke = true
      break
    end
  end
  if repeat_joke then
    next_number = math.random(1,#jokes)
    repeat_joke = false
    goto Check
  end

  ::Save::
  table.insert(jokes_told,tostring(next_number))
  while #jokes_told>repeat_threshold do table.remove(jokes_told, 1) end
  file_jokes_told = io.open(jokes_told_file,"w+")
  for i, joke_test in pairs(jokes_told) do
    file_jokes_told:write(joke_test.."\n")
  end
  io.close(file_jokes_told)

end

tell_joke = jokes[next_number]

for lc, line in pairs(tell_joke) do
  yield(channel.." "..line)
  if tell_joke[lc+1] then
    yield("/wait "..(string.len(line)/100)*delay_modifier)
  end
end
